server.port = 8888
server.max_clients = 10
log.file = gateway.log

sensor[0].name = TempSensor
sensor[0].min = 220
sensor[0].max = 380
sensor[0].interval = 2000

sensor[1].name = HumiSensor
sensor[1].min = 30
sensor[1].max = 90
sensor[1].interval = 3000

sensor[2].name = LightSensor
sensor[2].min = 50
sensor[2].max = 800
sensor[2].interval = 5000

sensor[3].name = PressureSensor
sensor[3].min = 900
sensor[3].max = 1100
sensor[3].interval = 4000

sensor[4].name = GasSensor
sensor[4].min = 0
sensor[4].max = 1000
sensor[4].interval = 600
